language: node_js
node_js:
  - 12

sudo: true

addons:
  chrome: stable

branches:
  only:
    - main

before_script:
  - npm install -g yarn
  - npm install -g @angular/cli
  - yarn install

script:
  - ng build
  - ng lint
  - yarn run test-headless